### PR TITLE
fixes GEN 2 cloudfunctions function not getting listed

### PR DESCRIPTION
**Pull request by ashutoshmore658**
This PR fixes following bug issue:
https://github.com/turbot/steampipe-plugin-gcp/issues/565

### CODE REVIEW

**Review by bigdatasourav — APPROVED** [review]

**Comment by misraved** [comment]
@ashutoshmore658 welcome to Steampipe and thank you so much for raising the PR 👍.

Could you please add the example queries in the PR removing the sensitive data?

**Comment by ashutoshmore658** [comment]
Sure @misraved  could you please elaborate ? exactly what are the example queries ?, so that I can get it in to the action.

**Comment by misraved** [comment]
@ashutoshmore658 please take a look at the following suggestions for the PR:
- Since we are using a new version of the cloud functions, I think it is important to verify if all the Gen 2 cloud functions are getting listed or not. Please add an example query that enlists both the Gen 1 and Gen 2 cloud functions.
- Use the `select * from gcp_cloudfunctions_function` query on the main and `ashutoshmore658:Gcp-CloudFunctions-Gen2-Flooding` branch to verify that other columns haven't been affected (difference in the datatype or output structure) by this change.

**Comment by ashutoshmore658** [comment]
Thank you for the detailed explanation @misraved , I will act accordingly.

**Comment by ashutoshmore658** [comment]
@misraved  I am adding some more commits in the current PR, but how to show the results, cause security reasons are involved ?

**Comment by misraved** [comment]
@ashutoshmore658 what commits are you trying to add? I feel the results are sufficient for the PR to be merged 👍.

**Comment by misraved** [comment]
@ashutoshmore658 we can go ahead and raise a new PR for those changes. Meanwhile, let me merge this PR 👍.

Great work 🎉 !!

**Pull request merged**
